export const UPDATE_POSTS = 'UPDATE_POSTS';

//login action types
export const LOGIN_START = 'LOGIN_START';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';

//Signu actio type

export const SIGNUP_START = 'SIGNUP_START';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILED = 'SIGNUP_FAILED';

export const AUTHENTICATE_USER = 'AUTHENTICATE_USER';
export const LOG_OUT = 'LOGOUT';
export const CLEAR_AUTH_STATE = 'CLEAR_AUTH_STATE';

export const EDIT_USER_SUCCESSFUL = 'EDIT_USER_SUCCESSFUL';
export const EDIT_USER_FAILED = 'EDIT_USER_FAILED';

export const USER_PROFILE_SUCCESS = 'USER_PROFILE_SUCCESS';
export const USER_PROFILE_FAILURE = 'USER_PROFILE_FAILURE';
export const FETCH_USER_PROFILE = 'FETCH_USER_PROFILE';

//friends
export const FETCH_FRIENDS_SUCCESS = 'FETCH_FRIENDS_SUCCESS';

export const ADD_FRIENDS_SUCCESS = 'ADD_FRIENDS_SUCCESS';
export const REMOVE_FRIENDS_SUCCESS = 'REMOVE_FRIENDS_SUCCESS';
